### PR TITLE
Moved Bootstrap to vendor bundle

### PR DESCRIPTION
**Pull request by stevepop**
Checklist for Pull request must be completed:
- [x] Tested code works
- [x] Checked nobody is working on same thing check issue log
- [x] There are no conflicts
- [x] you have detailed below what you have completed/added and if anything is required to be run i.e npm / migrate etc.

#### Please complete below what you have done/fixed for Pull Request:
- Separated bootstrap in webpack config  into vendor bundle to seprate from VueJS bundle
- Installed VueJS

### CODE REVIEW

**Comment by iiCe89** [comment]
@stevepop seems like a few things missing according to Bot or am i miss-reading

**Comment by stevepop** [comment]
The bot is using a different standard from lint. We may need to do a slight change in configuration or change stuff to satisfy Hound CI

**Comment by iiCe89** [comment]
@stevepop you happy for me to merge

**Comment by stevepop** [comment]
@iiCe89 Go ahead and merge

**Pull request merged**
